<?php
    session_start();
    unset($_SESSION['auth']);
    unset($_SESSION['id']);
    unset($_SESSION['name']);
    unset($_SESSION['mail']);
    header("refresh:5;url=index.html");
?>
感謝使用!<br>5秒後登出